# Generated by Django 5.2.6 on 2025-11-14 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myblog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-views', '-created_at']},
        ),
    ]
